### ISSUE TITLE
1.9.4-1.1.1 crashes dedicated Forge 1.9.4 build 1954 on startup

### ISSUE THREAD

**Issue by kreezxil** [werty1124/SimpleMagnet#1]
Issue:  Simple Magnets 1.9.4-1.1.1 crashes dedicated Forge 1.9.4 build 1954 on startup

https://gist.github.com/6f4eb671e8ef6bd12e28b9bbdcb47155

https://gist.github.com/209b24a927f43a9c59c0c5eef480e3ec

**Comment by werty1124** [comment]
Fixed in 1.9.4-1.1.2.

**Comment by kreezxil** [comment]
**IT'S BACK!**

Issue:  simple-magnet-1.9.4-1.1.3 crashes dedicated Forge 1.9.4 build 1954 on startup

crash report:
https://gist.github.com/92063cbb44da69cdca405ba861df0cd4

fml server latest:
https://gist.github.com/30a5bef3622b0384eadce33307c6a494

**Comment by werty1124** [comment]
@kreezxil  It's been fixed again. Sorry about that I fixed it client side the first time 1.1.4 fixes it server side
