### ISSUE TITLE
Crash in Multiplayer

### ISSUE THREAD

**Issue by tgstyle** [werty1124/SimpleMagnet#13]
This crash happens when putting the recipe in the crafting table, it works fine in Singleplayer.

simplemagnet-1.12.2-1.2.7

https://gist.github.com/tgstyle/799721d3955b3b41705dd7c002d6258f

**Comment by tgstyle** [comment]
Previous version works fine, appears to be something with the visual effect in 1.2.7.

**Comment by werty1124** [comment]
Fixed
