### ISSUE TITLE
Simple Magnet Ring

### ISSUE THREAD

**Issue by ifficles** [werty1124/SimpleMagnet#14]
Just a question, is the simple magnet ring recipe disabled?  I have baubles installed.  However, when I use the recipe to create the ring, there's nothing.  Just a blank square.

Please have a look, at the link below
https://www.4shared.com/s/fHe5nXaNOca

**Comment by werty1124** [comment]
Sorry for the late reply. I may have forgotten to add the recipe back. I'll take a look at it

**Comment by ifficles** [comment]
No worries.  I figured you would get to it when you could.  Thanks for checking

**Comment by ifficles** [comment]
Thanks for updating the recipe.
