### ISSUE TITLE
[Request] Item teleportation to player inventory

### ISSUE THREAD

**Issue by ghost** [werty1124/SimpleMagnet#16]
It would be great if the magnet teleported items within its radius to the players inventory, rather than having them pathfind and travel, especially on larger servers where everyone has a magnet. If the item traveling is still desireable, you could even add a config option to switch between the two modes.

For an implimentation of this feature (that has been abandoned by its author), you can check out the [Better Magnets](https://github.com/TheUnderTaker11/Better-Magnets) mod.

**Comment by werty1124** [comment]
Sorry for the late replay I forget to check this. This is a good idea, ill try to get it added ASAP

**Comment by werty1124** [comment]
done! in version 1.2.10
