### ISSUE TITLE
Bugs and Feature Request

### ISSUE THREAD

**Issue by jedirulez** [werty1124/SimpleMagnet#17]
First off great mod, thank you. 

Bugs: both of these bugs only happen when the config is changed for the instant pickup to inventory. 

1. When grabbing an item that is placed in the word using Draconic Evolution's "Place Item in World" feature and the magnet is enabled it will create a ghost duplicate the item(s). Attempting to use or move the ghost duplicate will make it disappear, so not a true dupe, but can be quite confusing. 

2. Items picked up by the magnet do not automatically go into a dank/null. This works fine with the config option for instant pickup left at default. 

Feature Requests:
It would be great to have a redstone controllable block that would disable the magnet in a configurable range around the block. 

Thanks again.

**Comment by werty1124** [comment]
I'll take a look at the two bugs you mentioned and try to get them fixed ASAP and I can definitely add a block to disable the magnet. I've been planning on adding a similar block but never got around to actually doing it.
