### ISSUE TITLE
Magnet Tooltip via JEI is misleading for some. 

### ISSUE THREAD

**Issue by StoneLegion** [werty1124/SimpleMagnet#20]
This might be a bit of a funny derp on some players. But more then one person now has asked why the magnet is disabled from crafting due to the enable/disable on/off feature of the magnet lol.

https://i.imgur.com/gwqksSN.png

I'm wondering if by default you can have it say enabled as when you do craft it, it's actually enabled by default or change it to on/off instead.

Thanks :)

**Comment by werty1124** [comment]
Sorry for the late reply. I don't check this as often as i should but i do see how it could get confusing.
