### ISSUE TITLE
Crash while picking

### ISSUE THREAD

**Issue by GlobbyPotato** [werty1124/SimpleMagnet#21]
Hi, just updated to v1.3.11 from v1.2.11 and got this crash as soon as magnet or ring tries to pick tossed items. Using also Baubles v1.52 (crashes with and without) and Forge v14.23.5.2825.

https://pastebin.com/ny747amT
https://pastebin.com/QkkCrAux

Thank you for the mod.

**Comment by werty1124** [comment]
Fixed in 1.3.12
