### ISSUE TITLE
Deleting Items

### ISSUE THREAD

**Issue by Jayceena** [werty1124/SimpleMagnet#6]
With the mod installed if I as a player try to drop an item (without (idk with) the magnet) the item is destroyed.

**Comment by Malkierian** [comment]
This is true regardless of whether you have the magnet or not, as well as whether you're using the item magnet or the ring magnet.  I posted details on the curse mod page.  If you try to drop items while in a GUI (furnace, chest, etc), it also either causes a crash or an infinite hang.
