### ISSUE TITLE
Crash when tossing items on the ground or into creative tabs.

### ISSUE THREAD

**Issue by Kashdeya** [werty1124/SimpleMagnet#8]
Starting a new modpack project. Was doing a little testing and got the crash.

Minecraft version: 1.10.2
Mod ver: 1.10.2-1.2.2
Baubles ver: 1.10.2-1.3.8

Crashlog:
http://pastebin.com/rFgc7wSF

Issues goes away when I remove Simple Magnet from the pack.

**Comment by ghost** [comment]
I also have this issue however I do not crash. Items simply vanish.

https://gist.github.com/HellishINC/9d3d8ad622f8f5d2eaf92c9c6639f7d1

**Comment by CaelThunderwing** [comment]
it seems to be related to Baubles and the API Version this mod uses thats why it disappears when you Remove Baubles or you remove this mod.

**Comment by ghost** [comment]
Thanks for the updates.

**Comment by werty1124** [comment]
@HellishINC I closed all the issues since they didn't seem to happen on the 1.12 version but let me know if you have any problems if you're still using the mod

**Comment by Murrlin** [comment]
MC 1.10.2, Forge 12.18.3.2511, Baubles 1.10.2-1.3.13, Mod version 1.2.2
tossing item with magnet on = crash.
